[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ny_pack_1"
version = "0.1.0"
description = "My first package!"
authors = [
    { name = "Nikhil Yadav", email = "nikhilyadav.uk@gmail.com" }
]